In [2]:
##Analyse Daten Weltbank

In [3]:
import pandas as pd
import os

In [4]:
df = pd.read_csv(r'C:\Users\phili\OneDrive\Desktop\Abschlussarbeit Weiterbildung\datasets\WDI - wichtige Daten\WDICSV.csv', 
                low_memory = False)

In [5]:
df.shape

(398468, 70)

In [6]:
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.471500,18.822373,19.302882,19.770426,20.120927,20.440680,20.817895,21.161010,21.532841,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.682625,7.953281,8.528101,8.878267,9.050266,9.111884,9.285654,9.403676,9.687390,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,39.163151,39.206303,39.406216,39.569413,39.958115,40.025590,40.203585,40.728295,41.118943,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,50.667516,52.598171,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.998179,35.240236,36.080572,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398463,Zimbabwe,ZWE,Women who believe a husband is justified in be...,SG.VAW.REFU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398464,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.400000,NaN,NaN,NaN,NaN,NaN,NaN
398465,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,33.700000,NaN,NaN,NaN,NaN,NaN,NaN
398466,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.916636,59.131787,59.318579,59.495248,59.675019,59.832577,59.955283,60.053675,60.155308,NaN
398467,Zimbabwe,ZWE,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,NaN,NaN,NaN,NaN,NaN,...,12000.000000,9200.000000,7200.000000,6200.000000,5200.000000,6200.000000,4700.000000,4400.000000,4400.000000,NaN

In [7]:
##Anzahl der Spalten eingrenzen

jahre = [str(i) for i in range(2001, 2016)]

spalten = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'] + jahre

In [8]:
df2 = df[spalten].copy()

In [9]:
df2.shape

(398468, 19)

In [10]:
df2.loc[(df2['Indicator Name'].str.contains('employment')), :]

,Country Name,Country Code,Indicator Name,Indicator Code,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
18,Africa Eastern and Southern,AFE,Adequacy of unemployment benefits and ALMP (% ...,per_lm_alllm.adq_pop_tot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,Africa Eastern and Southern,AFE,Benefit incidence of unemployment benefits and...,per_lm_alllm.ben_q1_tot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,Africa Eastern and Southern,AFE,Child employment in agriculture (% of economic...,SL.AGR.0714.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,Africa Eastern and Southern,AFE,"Child employment in agriculture, female (% of ...",SL.AGR.0714.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,Africa Eastern and Southern,AFE,"Child employment in agriculture, male (% of ma...",SL.AGR.0714.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398445,Zimbabwe,ZWE,"Vulnerable employment, male (% of male employm...",SL.EMP.VULN.MA.ZS,55.789294,56.057982,56.750572,57.291095,57.671637,57.804846,58.362298,59.127484,59.683532,59.733179,59.507598,59.805470,60.175340,60.639215,60.371454
398446,Zimbabwe,ZWE,"Vulnerable employment, total (% of total emplo...",SL.EMP.VULN.ZS,65.533311,65.725191,66.243464,66.649244,66.935105,66.992797,67.437145,67.967837,68.403275,68.434005,68.243606,68.394981,68.572309,68.829076,68.625240
398447,Zimbabwe,ZWE,"Wage and salaried workers, female (% of female...",SL.EMP.WORK.FE.ZS,23.127923,23.019995,22.653108,22.332970,22.131731,22.079565,21.752493,21.395707,21.049272,20.970324,21.068786,21.113506,21.166219,21.155940,21.320264
398448,Zimbabwe,ZWE,"Wage and salaried workers, male (% of male emp...",SL.EMP.WORK.MA.ZS,41.064716,40.808360,40.141461,39.577916,39.151188,38.912073,38.402266,37.604661,37.104416,37.082736,37.344464,36.837208,36.213850,35.503668,35.774139
398449,Zimbabwe,ZWE,"Wage and salaried workers, total (% of total e...",SL.EMP.WORK.ZS,31.927654,31.753056,31.267220,30.855258,30.546673,30.414271,30.013320,29.453894,29.051475,29.023534,29.221193,28.982598,28.692993,28.333681,28.539401

In [11]:
##es werden jetzt zwei Indikatoren ausgewählt

indikatoren = [
    'FP.CPI.TOTL.ZG',
    'SL.UEM.TOTL.ZS'
]

df3 = df2[
    df2['Indicator Code'].isin(indikatoren)
].copy()

In [12]:
df3 = df3.reset_index(drop=True)

In [13]:
df3

,Country Name,Country Code,Indicator Name,Indicator Code,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,5.840354,8.763755,7.449700,5.023421,8.558038,8.898164,8.450775,12.566645,8.954218,5.537538,8.971206,9.158708,5.748831,5.525819,5.098562
1,Africa Eastern and Southern,AFE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,7.553885,7.511493,7.472042,7.278522,7.100414,7.035601,6.980589,6.959262,7.029335,7.339489,7.303351,7.108737,6.889722,6.862429,6.930941
2,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,4.361529,3.188693,1.760904,0.694336,5.631634,4.415900,3.607368,8.452976,3.282440,1.784844,4.018699,4.578375,2.439201,1.768436,2.130817
3,Africa Western and Central,AFW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,4.465630,4.273921,4.168206,4.086989,4.096412,3.969002,3.948205,3.968089,4.004413,3.991792,3.970074,3.982914,3.710110,3.890183,4.172773
4,Arab World,ARB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.772204,1.832994,2.712592,3.632280,3.493685,3.544986,4.743906,11.270665,2.920897,3.911062,4.753164,4.611844,3.221978,2.899479,1.831352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,11.724000,11.839000,12.014000,12.131000,12.213000,12.349000,12.486000,12.656000,12.762000,12.777000,13.311000,13.473000,13.673000,13.467000,17.900000
528,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,21.393782,22.233345,21.401578,17.967789,18.324440,9.019572,10.657350,12.445579,13.395255,8.501761,6.429397,6.575900,6.977676,7.806876,10.110593
529,Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,13.404000,14.131000,14.704000,15.332000,15.900000,13.229000,10.559000,7.930000,10.583000,13.190000,10.548000,7.850000,7.272000,6.576000,5.951000
530,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.022670,3.466130,3.725327,1.634950,-0.197785,-2.430968
531,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,5.313000,5.005000,4.738000,4.390000,4.632000,4.767000,5.008000,5.401000,5.476000,5.469000,5.368000,5.057000,4.948000,4.774000,5.399000

In [14]:
##melt

df4 = pd.melt(
    df3,
    id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
    var_name='year',
    value_name='value'
)

df4['year'] = df4['year'].astype(int)

df4.head()

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
0,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,5.840354
1,Africa Eastern and Southern,AFE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,7.553885
2,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,4.361529
3,Africa Western and Central,AFW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,4.465630
4,Arab World,ARB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,1.772204

In [15]:
##Länderaggregate entfernen

laender = pd.read_csv(r'C:\Users\phili\OneDrive\Desktop\Abschlussarbeit Weiterbildung\datasets\WDI - wichtige Daten\WDICountry.csv')

gueltige_codes = laender.loc[
    laender['Region'].notna(),
    'Country Code'
]

df4 = df4[
    df4['Country Code'].isin(gueltige_codes)
].copy()

In [16]:
df4

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
98,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,NaN
99,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,7.973000
100,Albania,ALB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,3.107588
101,Albania,ALB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,18.570000
102,Algeria,DZA,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,4.225988
...,...,...,...,...,...,...
7975,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,17.900000
7976,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2015,10.110593
7977,Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,5.951000
7978,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2015,-2.430968
7979,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,5.399000

In [17]:
##erstellen der Liste aus dem IWF Datensatz um die Länder zu einem bestimmten Satz zu erstellen

liste_IWF = ['Slovak Republic',
 'Estonia, Republic of',
 'Czech Republic',
 'Latvia, Republic of',
 'Hungary',
 'Lithuania, Republic of',
 'Slovenia, Republic of',
 'Poland, Republic of',
 'United Kingdom',
 'United States',
 'Belgium',
 'Austria',
 'Germany',
 'Denmark',
 'France',
 'Luxembourg',
 'Italy',
 'Sweden',
 'Norway',
 'Netherlands, The',
 'Switzerland',
 'Canada',
 'Japan',
 'Finland',
 'Iceland',
 'Greece',
 'Ireland',
 'Spain',
 'Portugal',
 'New Zealand',
 'Australia',
 'Türkiye, Republic of',
 'Colombia',
 'Chile',
 'Costa Rica',
 'Mexico',
 'Israel',
 'Korea, Republic of']

In [18]:
##die Länder aus dem Weltbank-Datensatz

df4['Country Name'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'British Virgin Islands',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands',
       'Central African Republic', 'Chad', 'Channel Islands', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia',
       'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo',
       'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.',
       'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Naoero', 'Nepal',
       'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Northern Mariana Islands',
       'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico (US)', 'Qatar', 'Romania',
       'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia',
       'Solomon Islands', 'Somalia, Fed. Rep.', 'South Africa',
       'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis',
       'St. Lucia', 'St. Martin (French part)',
       'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)',
       'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [19]:
df5 = df4.loc[(df4['Country Name'].isin(liste_IWF)), :]

In [20]:
df5

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
118,Australia,AUS,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,4.407130
119,Australia,AUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,6.747000
120,Austria,AUT,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,2.650001
121,Austria,AUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,4.007000
134,Belgium,BEL,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,2.469261
...,...,...,...,...,...,...
7923,Switzerland,CHE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,4.801000
7956,United Kingdom,GBR,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2015,0.368047
7957,United Kingdom,GBR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,5.552000
7958,United States,USA,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2015,0.118627
7959,United States,USA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,5.280000

In [21]:
df5['Country Name'].unique()

array(['Australia', 'Austria', 'Belgium', 'Canada', 'Chile', 'Colombia',
       'Costa Rica', 'Denmark', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Japan',
       'Luxembourg', 'Mexico', 'New Zealand', 'Norway', 'Portugal',
       'Slovak Republic', 'Spain', 'Sweden', 'Switzerland',
       'United Kingdom', 'United States'], dtype=object)

In [22]:
liste_IWF = sorted(liste_IWF)

In [23]:
liste_IWF

['Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Chile',
 'Colombia',
 'Costa Rica',
 'Czech Republic',
 'Denmark',
 'Estonia, Republic of',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hungary',
 'Iceland',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Korea, Republic of',
 'Latvia, Republic of',
 'Lithuania, Republic of',
 'Luxembourg',
 'Mexico',
 'Netherlands, The',
 'New Zealand',
 'Norway',
 'Poland, Republic of',
 'Portugal',
 'Slovak Republic',
 'Slovenia, Republic of',
 'Spain',
 'Sweden',
 'Switzerland',
 'Türkiye, Republic of',
 'United Kingdom',
 'United States']

In [24]:
##Länder, die fehlen:

fehlende_laender = sorted(
    set(liste_IWF) - set(df5['Country Name'])
)

print(fehlende_laender)

['Czech Republic', 'Estonia, Republic of', 'Korea, Republic of', 'Latvia, Republic of', 'Lithuania, Republic of', 'Netherlands, The', 'Poland, Republic of', 'Slovenia, Republic of', 'Türkiye, Republic of']

In [25]:
##Länder angleichen

namen = {
    'Czechia': 'Czech Republic',
    'Estonia': 'Estonia, Republic of',
    'Korea, Rep.': 'Korea, Republic of',
    'Latvia': 'Latvia, Republic of',
    'Lithuania': 'Lithuania, Republic of',
    'Netherlands': 'Netherlands, The',
    'Poland': 'Poland, Republic of',
    'Slovenia': 'Slovenia, Republic of',
    'Turkiye': 'Türkiye, Republic of'
}

df4['Country Name'] = df4['Country Name'].replace(namen)

In [30]:
df4['Country Name'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'British Virgin Islands',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands',
       'Central African Republic', 'Chad', 'Channel Islands', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia, Republic of', 'Eswatini',
       'Ethiopia', 'Faroe Islands', 'Fiji', 'Finland', 'France',
       'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland',
       'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.",
       'Korea, Republic of', 'Kosovo', 'Kuwait', 'Kyrgyz Republic',
       'Lao PDR', 'Latvia, Republic of', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania, Republic of', 'Luxembourg',
       'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Naoero', 'Nepal', 'Netherlands, The', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland, Republic of', 'Portugal', 'Puerto Rico (US)', 'Qatar',
       'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovak Republic',
       'Slovenia, Republic of', 'Solomon Islands', 'Somalia, Fed. Rep.',
       'South Africa', 'South Sudan', 'Spain', 'Sri Lanka',
       'St. Kitts and Nevis', 'St. Lucia', 'St. Martin (French part)',
       'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Türkiye, Republic of', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Viet Nam',
       'Virgin Islands (U.S.)', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [32]:
df5 = df4.loc[(df4['Country Name'].isin(liste_IWF)), :].copy()

In [33]:
df5

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
118,Australia,AUS,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,4.407130
119,Australia,AUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,6.747000
120,Austria,AUT,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,2.650001
121,Austria,AUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2001,4.007000
134,Belgium,BEL,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2001,2.469261
...,...,...,...,...,...,...
7943,"Türkiye, Republic of",TUR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,10.304000
7956,United Kingdom,GBR,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2015,0.368047
7957,United Kingdom,GBR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,5.552000
7958,United States,USA,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2015,0.118627
7959,United States,USA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2015,5.280000

In [35]:
df5['Country Name'].unique()

array(['Australia', 'Austria', 'Belgium', 'Canada', 'Chile', 'Colombia',
       'Costa Rica', 'Czech Republic', 'Denmark', 'Estonia, Republic of',
       'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland',
       'Ireland', 'Israel', 'Italy', 'Japan', 'Korea, Republic of',
       'Latvia, Republic of', 'Lithuania, Republic of', 'Luxembourg',
       'Mexico', 'Netherlands, The', 'New Zealand', 'Norway',
       'Poland, Republic of', 'Portugal', 'Slovak Republic',
       'Slovenia, Republic of', 'Spain', 'Sweden', 'Switzerland',
       'Türkiye, Republic of', 'United Kingdom', 'United States'],
      dtype=object)

In [ ]:
##Länderabgleich abgeschlossen

In [36]:
##nan - Werte ermitteln

In [37]:
df5.isna().sum()

Country Name      0
Country Code      0
Indicator Name    0
Indicator Code    0
year              0
value             0
dtype: int64

In [38]:
df5.shape

(1140, 6)

In [39]:
df5.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
year                int32
value             float64
dtype: object

In [40]:
### keine nan und shape und dtypes sind korrekt. 
### jetzt kann der SQL-Export gemacht werden

In [41]:
df5.to_csv(
    'Weltbank_MySQL.csv',
    index=False,
    encoding='utf-8'
)

In [42]:
print(os.getcwd())

C:\Users\phili\Final Project